name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Navigate to frontend and create .env
        run: |
          cd frontend
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env
      
      - name: Install dependencies
        run: |
          cd frontend
          npm i
          
      - name: Build project
        run: |
          cd frontend
          npm run build
          
      - name: Deploy to Cloudflare Pages
        run: |
          cd frontend
          npx wrangler pages publish ./dist --project-name ees-alum --branch main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
